<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="style.css">
    <title>Histoire</title>
</head>
<body>

    <?php include 'inc.header.php' ?>
    <?php include 'inc.menu.php'?>

    <main>
    <h1>Une histoire méconnue</h1>

        <img src="pages/images/histoire.jpg" id="histoire">
        <h2>Les débuts</h2>
        <p>Les premiers édifices fortifiés construits sur le site où se trouve aujourd'hui Varsovie furent ceux de Bródno (ixe et xe siècles) et de Jazdów (xiie et xiiie siècles)8. Après l'attaque et la destruction de Jazdów, une nouvelle colonie semblable fut créée sur le site d'un petit village de pêcheurs appelé Warszowa. Vers 1300, Boleslas II de Mazovie, prince de Płock, établit la ville actuelle de Varsovie. Au début du xive siècle, elle devint l'un des sièges des ducs de Mazovie, puis la capitale de la Mazovie en 14138. À cette époque, l'économie de la ville reposait sur l'artisanat et le commerce.</p>

        <h2>Du xvie au xviiie siècle</h2>
        <p>À la suite de l'extinction de la ligne ducale, le duché de Mazovie fut intégré à la couronne polonaise en 15268. Trois ans plus tard, la Diète générale fut réunie pour la première fois à Varsovie, qui devint son siège permanent à partir de 15698, après avoir été brièvement occupée par les troupes alliées de la Suède et du Brandebourg durant la Première guerre du Nord.</p>
        <p>En 1573, la ville donna son nom à la Confédération de Varsovie, établissant officiellement la liberté de religion dans la République des Deux Nations. Grâce à sa situation médiane entre les capitales de ces deux nations (Cracovie pour la Pologne et Vilnius pour la Lituanie), Varsovie devint la capitale de la République unifiée. La couronne polonaise y fut transférée en 1596, quand le roi Sigismond Vasa déplaça la cour de Cracovie à Varsovie.</p>
        <p>Dans les années qui suivirent, la ville s'étendit sur les terres de l'actuelle banlieue, sous forme de vastes domaines privés indépendants, possédés par la haute noblesse et administrés selon leurs propres lois. Entre 1655 et 1658, la ville fut assiégée trois fois et trois fois elle fut prise et pillée par les troupes suédoises, brandebourgeoises et transylvaniennes.</p>
        <p>Pendaison de traîtres "in effigie" lors de l'insurrection de Varsovie en 1794. Les partisans de la Confédération de Targowica, responsable de la seconde partition de la Pologne, sont devenus des ennemis publics. S'ils ne pouvaient pas être capturés, leurs portraits ont été pendus à leur place.<br>
        En 1700, la Grande guerre du Nord éclata. La ville fut assiégée à plusieurs reprises et dut payer de fortes contributions.</p>
        <p>Stanislas II, le dernier roi indépendant de la République des Deux nations, remodela l'intérieur du palais royal, et il fit de la ville un centre important dans le domaine artistique et culturel11,12, ce qui valut à Varsovie le surnom de « Paris oriental ».</p>

        <h2>xixe siècle</h2>
        <p>Varsovie est restée la capitale de la République des Deux Nations jusqu'en 1795, lorsqu'elle fut incorporée au Royaume de Prusse pour devenir le chef-lieu de la province de Prusse-Méridionale (en allemand : Südpreußen). Libérée par l'armée de Napoléon en 1806, Varsovie devint la capitale du nouveau Duché de Varsovie l'année suivante.</p>
        <p>Après le Congrès de Vienne de 1815, Varsovie devint le centre du Royaume du Congrès, une monarchie constitutionnelle liée par une « union personnelle » à l'Empereur de Russie, qui prit également de titre de « Roi de Pologne ». Durant une dizaine d'années, Varsovie connut un essor important (création de l'Université Royale et de nombreux instituts supérieurs, des bourses des marchandises et de la monnaie, de la Banque de Pologne, développement du commerce, de l'industrie et des transports…) mais l'arrivée au pouvoir de Nicolas Ier, monarque absolu ne tolérant aucune limitation à son pouvoir, marqua la fin de cette période libérale : le tsar envoya à Varsovie son frère cadet Constantin en qualité de vice-roi de Pologne et le mécontentement des élites polonaises grandit rapidement, jusqu'à aboutir à l'Insurrection de Novembre. En janvier 1831, le tsar, qui venait d'être déposé par la Diète pour avoir transgressé à de nombreuses reprises la Constitution, envoya des troupes pour mater la rébellion. Les Russes entrèrent dans Varsovie le 8 septembre 1831. La Pologne fut alors soumise à une intense russification qui aboutit à la disparition officielle du Royaume de Pologne en 1867 sous le règne de l'Empereur Alexandre II, malgré l'instauration d'un gouvernement national clandestin à Varsovie et plusieurs tentatives de soulèvement.</p>
       <p>Varsovie a toutefois prospéré à la fin du xixe siècle, avec le maire Sokrat Starynkiewicz (pl), un général d'origine russe nommé par le tsar Alexandre III. Avec lui, Varsovie fut doté d'un réseau de distribution d'eau et d'égouts conçus et construits par l'ingénieur anglais William Lindley et son fils William Heerlein Lindley. La ville bénéficia aussi de la modernisation et de l'expansion des tramways, de l'éclairage public et des usines à gaz.</p>
        <p>Le recensement de l'Empire russe de 1897 dénombrait 626 000 personnes vivant à Varsovie, ce qui en faisait alors la troisième plus grande ville de l'Empire, après Saint-Pétersbourg et Moscou.</p>

        <h2>xxe siècle</h2>
        <p>Durant la Première Guerre mondiale, les troupes de l'Empire allemand échouèrent à prendre Varsovie lors de la bataille de la Vistule de septembre-octobre 1914, mais ils y parvinrent un an plus tard à la suite de la défaite de l'armée russe à la bataille de Varsovie d'août-septembre 1915.</p>
        <p>Le 3 mars 1918, la toute nouvelle République socialiste fédérative soviétique de Russie abandonna la Pologne à l'Allemagne par la signature du Traité de Brest-Litovsk qui mettait fin aux hostilités germano-russes. Six mois plus tard, à la faveur de la Révolution allemande de 1918-1919 qui précipita la fin de la guerre, le maréchal Józef Piłsudski et le général Kazimierz Sosnkowski furent libérés de la forteresse de Magdebourg où ils étaient emprisonnés ; ils arrivèrent à Varsovie le 10 novembre 1918. Le lendemain 11 novembre 1918, alors que le nouveau pouvoir allemand signait l'Armistice avec la France et l'Angleterre dans la clairière de l'Armistice, le Conseil de Régence polonais transmit les pleins pouvoirs à Piłsudski, personnage hautement charismatique qui apparaissait comme l'homme providentiel de la Pologne ressuscitée. Varsovie redevint capitale le jour même avec l'instauration de la deuxième république de Pologne immédiatement proclamée par Piłsudski.</p>
        <p>L'histoire contemporaine de la civilisation connaît peu d'événements d'une importance plus grande que celle de la bataille de Varsovie de 1920 et aucune dont l'importance est moins appréciée.</p>
        <p>Au cours de la Guerre soviéto-polonaise de 1920 qui suivit, l'immense bataille de Varsovie fut menée dans la banlieue est de la ville et la capitale fut défendue avec succès contre l'Armée rouge16. En remportant cette victoire, la Pologne porta un coup sérieux à l'idéologie d'« exportation de la Révolution » qui prévalait alors en Russie soviétique.</p>
        <p>Pendant la Seconde Guerre mondiale, la Pologne centrale, qui comprenait Varsovie, passa sous le contrôle du « Gouvernement général de Pologne » établi à Cracovie et administré par le Reichsleiter Hans Frank. Tous les établissements d'enseignement supérieur furent fermés et la population juive de Varsovie – plusieurs centaines de milliers, environ 30 % de la population de la ville – parqués dans le ghetto de Varsovie18. Le 22 juillet 1942 les nazis lancèrent la Grande Action. Les juifs du ghetto sont rassemblés sur l'Umschlagplatz, rue Stawki, puis déportés vers le camp d'extermination de Treblinka. Quand l'ordre vint d'anéantir définitivement le ghetto dans le cadre de la « Solution finale », le 19 avril 1943, les combattants juifs lancèrent l'insurrection du ghetto de Varsovie19. Malgré la faible puissance de feu et l'infériorité numérique, le ghetto tint pendant près d'un mois19. À la fin des combats, presque tous les survivants furent massacrés, seuls quelques-uns réussirent à s'échapper ou à se cacher19,20. La population juive, qui était la plus nombreuse de toute l'Europe avant 1939, fut exterminée par les nazis. Aujourd'hui, de nombreux touristes, surtout ceux de la diaspora, visitent le cimetière de Powązki, le monument de l'Umschlagplatz et le cimetière juif de Varsovie.</p>
        <p>La résistance polonaise déclencha l'Insurrection de Varsovie le 1er août 1944. Sachant que Staline était hostile à l'idée d'une Pologne indépendante, le gouvernement polonais en exil à Londres ordonna à l'Armée de l'intérieur (AK) de prendre le contrôle de Varsovie avant l'arrivée de l'Armée rouge22. La résistance parvint à prendre le contrôle de quelques quartiers situés à l'ouest de la Vistule au cours des quatre premiers jours, puis dut rapidement se replier pour tenter de tenir ses positions face à la riposte allemande, qui fut d'une sauvagerie effroyable jusqu'à la fin septembre, fusillant sur place les combattants, tuant les blessés et les soignants. L'insurrection dura au total 63 jours. Les troupes soviétiques qui se trouvaient aux portes de la ville dès le 10 septembre ne tentèrent rien pour soutenir le mouvement des insurgés. Après la capitulation des dernières poches de résistance, Adolf Hitler ordonna de raser entièrement la ville et de transporter les collections des bibliothèques et des musées en Allemagne, ou plus simplement de les brûler. Les monuments et les édifices publics furent dynamités par les troupes allemandes spéciales connues sous le nom Verbrennungs- und Vernichtungskommando (détachement d'incendie et de destruction), tandis que toute la population civile était expulsée.</p>
        <p>Staline laissa ses troupes attendre plusieurs mois l'écrasement complet du soulèvement et la destruction de la ville avant d'y pénétrer, laissant près de 200 000 Polonais se faire massacrer, civils pour la plupart23. Les troupes de l'Armée rouge finirent par « libérer » Varsovie le 17 janvier 1945 : le premier front biélorusse et une unité de combat polonaise pro-soviétique prirent possession d'une ville détruite à 85 pour cent et totalement désertée — les 350 000 survivants avaient fui ou avaient été déportés en Allemagne —, tandis qu'au nord de la ville, les troupes du deuxième front biélorusse entrèrent à Modlin.</p>
        <p>Dès le 5 novembre 1944, la Société des architectes de la République de Pologne s'était réunie à Lublin pour envisager la reconstruction de la capitale. Le nouveau régime communiste mis en place par les Soviétiques décida de lancer de grands projets de construction de logements préfabriqués pour remédier à la pénurie de logements, ainsi que d'autres bâtiments typiques d'une ville du Bloc de l'Est, tels que le Palais de la culture et de la science. La ville reprit peu à peu son rôle de capitale politique et économique.</p>
        <p>Les travaux de reconstruction de la Vieille ville débutèrent immédiatement, et la première phase des travaux fut achevée dès 1953. Deux ans plus tard, la cathédrale et plusieurs églises furent à leur tour achevées. La décision de reconstruire le palais royal ne fut prise qu'en 1971 et les derniers travaux durèrent jusqu'en 1988. Si la Vieille ville fut entièrement reconstruite à l'identique, tout comme de nombreux édifices publics, palais, hôtels particuliers et églises, également restaurés ou reconstruits sous leur forme originelle, certains des bâtiments du xixe siècle conservés au lendemain de la guerre dans un état qui aurait pu laisser envisager une reconstruction ont néanmoins été détruits dans les années 1950 et 1960 (c'est le cas du Palais de Léopold Kronenberg, par exemple.</p>
        <p>En 1979, moins d'un an après être devenu pape, Jean-Paul II se rendit à Varsovie et y célébra une messe sur la Place de la Victoire. Il termina son sermon par ces mots : « Et je crie, moi, fils de la terre polonaise, et en même temps moi, le pape Jean-Paul II, je crie du plus profond de ce millénaire, je crie la veille de la Pentecôte : Que descende ton Esprit ! Que descende ton Esprit ! Et qu’il renouvelle la face de la terre de cette terre25 ! » Les Polonais interprétèrent cette parole comme un encouragement à amorcer les changements démocratiques auxquels aspiraient la société polonaise et comme un soutien au syndicat clandestin Solidarność.</p>


        </main>

    <?php include 'inc.footer.php' ?>


</body>
</html>
